// Handleliste-data. Ren JSON-struktur – visningen bygges av skriptet i handleliste.html.
// Hvert element har både vendor (smak | oda | manuelt) og meal (middag | lunsj | nattmat),
// slik at listen kan grupperes begge veier. Priser i hele kroner; buy/note/product kan inneholde HTML.
window.HANDLELISTE_DATA = {
  "updated": "Priser innhentet 15. august 2026",
  "groupings": {
    "vendor": {
      "label": "Innkjøpssted",
      "groups": [
        {
          "key": "smak",
          "title": "Smak av Italia",
          "sub": "italienske spesialiteter",
          "note": "Nettbutikk: <a href=\"https://smakavitalia.no\" target=\"_blank\" rel=\"noopener\">smakavitalia.no</a> med klikk &amp; hent og levering. Butikker i Oslo bl.a. Vulkan (Maridalsveien 15C), Løren, Røa Torg og Lambertseter · tlf. 930 32 929. Fersk mozzarella og burrata leveres butikkene på fredager – reserver og hent fredag 21. august."
        },
        {
          "key": "oda",
          "title": "Oda",
          "sub": "dagligvarer med hjemlevering",
          "note": "<a href=\"https://oda.com/no/\" target=\"_blank\" rel=\"noopener\">oda.com</a> – hjemlevering i Oslo. Bestill leveringsvindu i god tid; ferskvarer leveres onsdag 19. august (jf. produksjonsplanen). Varene merket «Lunsj» og «Nattmat» bestilles i samme levering. Prisene er bekreftet 15. august og kan endres noe."
        },
        {
          "key": "manuelt",
          "title": "Manuelt",
          "sub": "grønnsakshandler, fiskehandler, bakeri og Vinmonopolet",
          "note": "Friske urter kjøpes hos grønnsakshandler (f.eks. Grønland) og feldsalatmiksen hos Meny (fredag) – all annen frukt og grønt ligger i Oda-bestillingen. Laksen bestilles hos fiskehandler senest mandag 17. august; lunsjens surdeigs-ciabatta (merket «Lunsj») avtales med bakeri samme dag. Vinen kjøpes på Vinmonopolet."
        }
      ]
    },
    "meal": {
      "label": "Måltid",
      "groups": [
        {
          "key": "middag",
          "title": "Middagsbuffet lørdag",
          "sub": "hele buffeten · 76 gjester",
          "note": "Alle varer til hovedbuffeten, sortert etter innkjøpssted (se merkene). Delte basisvarer (salt, sukker, smør og olje) står her – lunsjens andel er dekket av marginene og telles ikke på nytt."
        },
        {
          "key": "lunsj",
          "title": "Lunsj lørdag",
          "sub": "grillet biff-ciabatta · 45 gjester",
          "note": "Egen kasse/stasjon, jf. produksjonsplanen. Sandwichen bygges med dijonsennep, biff, karamellisert løk, tomatskiver og ruccola (à la Kitchen Cowboys). Brødet er surdeigs-ciabatta som spesialbestilles hos bakeri – avtal senest mandag 17. august, hent lørdag morgen. Vegetarvarianten (2 porsjoner) er ciabatta med tomat, mozzarella, pesto og basilikum; tomat, pesto og basilikum dekkes av marginene i hovedbuffeten, så kun én ekstra mozzarellakule må kjøpes. Smør, olivenolje og sukker til løken er dekket av marginene og telles ikke på nytt."
        },
        {
          "key": "nattmat",
          "title": "Nattmat lørdag kveld",
          "sub": "pølser i brød/lompe · ca. 50–55 sene gjester",
          "note": "Kjøpes med Oda-leveringen onsdag 19. august. Hovedpølsen skal være merket gluten- og laktosefri – mange norske grill- og wienerpølser er det, men les etiketten. Vegetar- og kyllingpølsene varmes i egen liten kjele med egen klype; de glutenfrie brødene serveres fra egen pose/kurv. Konkrete produkter er lagt i Oda-handlekurven 18. august; hovedpølsene (Gilde) er merket gluten- og laktosefrie, men les etiketten ved levering."
        }
      ]
    }
  },
  "tags": {
    "smak": "Smak av Italia",
    "oda": "Oda",
    "manuelt": "Manuelt",
    "middag": "Middag",
    "lunsj": "Lunsj",
    "nattmat": "Nattmat"
  },
  "items": [
    {
      "id": "prosciutto",
      "vendor": "smak",
      "meal": "middag",
      "qty": "1,0 kg",
      "name": "Prosciutto di Parma",
      "aria": "Prosciutto di Parma kjøpt",
      "product": "<a href=\"https://smakavitalia.no/prosciutto-di-parma-18mnd-100g\" target=\"_blank\" rel=\"noopener\">Prosciutto di Parma 18 mnd, skivet (Smak av Italia)</a>",
      "price": 920,
      "buy": "10 × 92 kr (100 g)"
    },
    {
      "id": "coppa",
      "vendor": "smak",
      "meal": "middag",
      "qty": "700 g",
      "name": "Coppa",
      "aria": "Coppa kjøpt",
      "product": "<a href=\"https://smakavitalia.no/coppa-80g-cavalier-u-boschi\" target=\"_blank\" rel=\"noopener\">Coppa, Cavalier U. Boschi, skivet</a>",
      "price": 612,
      "buy": "9 × 68 kr (80 g)"
    },
    {
      "id": "salami-sterk",
      "vendor": "smak",
      "meal": "middag",
      "qty": "600 g",
      "name": "Sterk italiensk salami",
      "aria": "Sterk italiensk salami kjøpt",
      "product": "<a href=\"https://smakavitalia.no/Produkt/358/80748236/Salame-piccante-gigante-Franchi-Salumi\" target=\"_blank\" rel=\"noopener\">Salame piccante Oppskåret, Franchi Salumi (løsvekt)</a>",
      "price": 354,
      "buy": "600 g × 590 kr/kg",
      "note": "Løsvekt 590 kr/kg, kuttes i ferskvaredisken. Mulig kampanjepris – bekreft ved bestilling."
    },
    {
      "id": "parmigiano",
      "vendor": "smak",
      "meal": "middag",
      "qty": "1,6 kg",
      "name": "Parmigiano Reggiano",
      "aria": "Parmigiano Reggiano kjøpt",
      "product": "<a href=\"https://smakavitalia.no/parmigiano-reggiano-21-24-mnd-dop-ca-1kg-gennari\" target=\"_blank\" rel=\"noopener\">Parmigiano Reggiano 21-24 mnd DOP ca 1 kg – Caseificio Gennari</a>",
      "price": 720,
      "buy": "1,6 kg × 450 kr/kg",
      "note": "Behov: ca. 1,47 kg (antipasti 600 g + polpette 320 g + pasta 550 g). Be om ett stykke à ca. 1,1 kg og ett à ca. 500 g, betales etter faktisk vekt."
    },
    {
      "id": "pecorino",
      "vendor": "smak",
      "meal": "middag",
      "qty": "600 g",
      "name": "Pecorino Romano DOP",
      "aria": "Pecorino Romano DOP kjøpt",
      "product": "<a href=\"https://smakavitalia.no/pecorino-romano-dop-crudo-ca-400gr-agriexport-sardegna\" target=\"_blank\" rel=\"noopener\">Pecorino Romano DOP &#x27;Crudo&#x27; ca 400 g – Agriexport Sardegna</a>",
      "price": 432,
      "buy": "2 × 216 kr (ca 400 g)",
      "note": "2 × ca. 400 g ≈ 800 g (200 g margin); kan også bestilles som ett 800 g-stykke."
    },
    {
      "id": "taleggio",
      "vendor": "smak",
      "meal": "middag",
      "qty": "700 g",
      "name": "Taleggio DOP",
      "aria": "Taleggio DOP kjøpt",
      "product": "<a href=\"https://smakavitalia.no/Produkt/209/80749902/Taleggio-Giallo-DOP-ca-2kg-Castagna\" target=\"_blank\" rel=\"noopener\">Taleggio DOP Oppskåret – Castagna (skåret fra hjul)</a>",
      "price": 294,
      "buy": "700 g × 420 kr/kg",
      "note": "Løsvekt – bestill 700 g direkte."
    },
    {
      "id": "mozzarella-fersk",
      "vendor": "smak",
      "meal": "middag",
      "qty": "2,0 kg",
      "name": "Fersk mozzarella",
      "aria": "Fersk mozzarella kjøpt",
      "product": "<a href=\"https://smakavitalia.no/Produkt/126/809951909/Mozzarella-di-Bufala-Campana-DOP-125gr-Campania-Felix\" target=\"_blank\" rel=\"noopener\">Mozzarella di Bufala Campana DOP 125 g – Campania Felix</a>",
      "price": 624,
      "buy": "16 × 39 kr (125 g kule i lake)",
      "note": "Bøffelmozzarella DOP. Fersk levering til butikkene på fredager – kjøp fredag 21.8 og ring og reserver 16 stk (tlf. 930 32 929)."
    },
    {
      "id": "burrata",
      "vendor": "smak",
      "meal": "middag",
      "qty": "1,5 kg",
      "name": "Burrata",
      "aria": "Burrata kjøpt",
      "product": "<a href=\"https://smakavitalia.no/burrata-fresca-125g-ignalat\" target=\"_blank\" rel=\"noopener\">Burrata fresca 125 g – Ignalat (Puglia)</a>",
      "price": 576,
      "buy": "12 × 48 kr (125 g)",
      "note": "Fersk levering fredager – reserver 12 stk samtidig med mozzarellaen."
    },
    {
      "id": "ricotta",
      "vendor": "smak",
      "meal": "middag",
      "qty": "1,5 kg",
      "name": "Ricotta",
      "aria": "Ricotta kjøpt",
      "product": "<a href=\"https://smakavitalia.no/Produkt/242/80750685/Riccotta-250g-Valcolatte\" target=\"_blank\" rel=\"noopener\">Ricotta 250 g – Valcolatte</a>",
      "price": 342,
      "buy": "6 × 57 kr (250 g)",
      "note": "Ordinær pris lagt til grunn; per 15.8 kampanje 48 kr/stk."
    },
    {
      "id": "strozzapreti",
      "vendor": "smak",
      "meal": "middag",
      "qty": "3,5 kg",
      "name": "Tørr pasta (strozzapreti)",
      "aria": "Tørr pasta (strozzapreti) kjøpt",
      "product": "<a href=\"https://smakavitalia.no/e-caserecce\" target=\"_blank\" rel=\"noopener\">e Caserecce – La Fabbrica della Pasta di Gragnano</a>",
      "price": 252,
      "buy": "7 × 36 kr (500 g)",
      "note": "Strozzapreti finnes ikke hos Smak av Italia – caserecce fra Gragnano er erstatningen (samme rolle i retten). Skalert opp fra 3,0 kg: eneste pastarett, mange fyller tallerkenen her (oppskriften bruker 3,4 kg)."
    },
    {
      "id": "pizzamel",
      "vendor": "smak",
      "meal": "middag",
      "qty": "5 kg",
      "name": "Hvetemel / pizzamel tipo 00",
      "aria": "Hvetemel / pizzamel tipo 00 kjøpt",
      "product": "<a href=\"https://smakavitalia.no/professional-pizzamel-tipo-00-rod-5kg-pivetti\" target=\"_blank\" rel=\"noopener\">Pivetti Professional Pizzamel «Tipo 00» Rød</a>",
      "price": 174,
      "buy": "1 × 174 kr (5 kg)",
      "note": "Flyttet fra Oda. Focaccia trenger 3,8 kg; melet er laget for 24–36 t heving og passer kaldhevingen."
    },
    {
      "id": "pesto-genovese",
      "vendor": "smak",
      "meal": "middag",
      "qty": "900 g",
      "name": "Pesto genovese",
      "aria": "Pesto genovese kjøpt",
      "product": "<a href=\"https://smakavitalia.no/pesto-alla-genovese-500g-gran-cucina\" target=\"_blank\" rel=\"noopener\">Pesto alla Genovese – Gran Cucina</a>",
      "price": 597,
      "buy": "3 × 199 kr (500 g)",
      "note": "Pastaen bruker 900 g (skalert opp med pastaen); resten er margin til lunsjens vegetar-ciabatta og søl. Lavt lagerantall enkelte butikker – bestill tidlig."
    },
    {
      "id": "pesto-gf-lf",
      "vendor": "smak",
      "meal": "middag",
      "qty": "450 g",
      "name": "Pesto, gluten- og laktosefri (til laksen)",
      "aria": "Pesto, gluten- og laktosefri (til laksen) kjøpt",
      "product": "<a href=\"https://smakavitalia.no/pesto-vegan-180g-oko-la-selva\" target=\"_blank\" rel=\"noopener\">Pesto Vegan Øko – La Selva</a>",
      "price": 207,
      "buy": "3 × 69 kr (180 g)",
      "note": "Vegansk øko-pesto: olivenolje, basilikum, pinjekjerner, salt, hvitløk, sitron – uten melk og gluten iht. ingredienslisten. Les etiketten på pakken før servering til allergigjestene."
    },
    {
      "id": "passata",
      "vendor": "smak",
      "meal": "middag",
      "qty": "5,1 kg",
      "name": "Passata / knuste tomater",
      "aria": "Passata / knuste tomater kjøpt",
      "product": "<a href=\"https://smakavitalia.no/polpa-di-pomodoro-425g-oko-la-selva\" target=\"_blank\" rel=\"noopener\">La Selva Polpa di pomodoro Øko (hakkede tomater)</a>",
      "price": 324,
      "buy": "12 × 27 kr (425 g glass)",
      "note": "Polpa (hakkede tomater); 12 × 425 g = 5,1 kg. Tomatbasen er halvert etter at lasagnen gikk ut. Ren passata finnes samme sted til 33 kr/glass."
    },
    {
      "id": "tomatpure",
      "vendor": "smak",
      "meal": "middag",
      "qty": "150 g",
      "name": "Tomatpuré",
      "aria": "Tomatpuré kjøpt",
      "product": "<a href=\"https://smakavitalia.no/concentrato-di-pomodoro-200g-la-selva\" target=\"_blank\" rel=\"noopener\">La Selva Concentrato di pomodoro Øko</a>",
      "price": 36,
      "buy": "1 × 36 kr (200 g)"
    },
    {
      "id": "evoo-finishing",
      "vendor": "smak",
      "meal": "middag",
      "qty": "2,0 l",
      "name": "Extra virgin olivenolje (kalde retter/finish)",
      "aria": "Extra virgin olivenolje (kalde retter/finish) kjøpt",
      "product": "<a href=\"https://smakavitalia.no/fruttato-3l-bag-in-box-gugliemi\" target=\"_blank\" rel=\"noopener\">Guglielmi Fruttato, extra virgin, bag-in-box</a>",
      "price": 785,
      "buy": "1 × 785 kr (3 l boks)",
      "note": "3 l bag-in-box dekker 2 l-behovet; overskuddet (ca. 1 l) går til steking, se raden under."
    },
    {
      "id": "olivenolje-steking",
      "vendor": "smak",
      "meal": "middag",
      "qty": "1,0 l",
      "name": "Olivenolje til steking/tomatbase",
      "aria": "Olivenolje til steking/tomatbase kjøpt",
      "product": "<a href=\"https://smakavitalia.no/selezione-1000ml-frantoi-cutrera\" target=\"_blank\" rel=\"noopener\">Frantoi Cutrera «Selezione» extra virgin, 1000 ml</a>",
      "price": 272,
      "buy": "1 × 272 kr (1 l)",
      "note": "Erstatter lavprisoljen fra Oda. Totalt kjøpes nå 4,0 l olje (3 l boks + 1 l denne) mot et beregnet behov på ca. 3,7 l – resten av stekebehovet tas fra 3 l-boksens margin."
    },
    {
      "id": "balsamicokrem",
      "vendor": "smak",
      "meal": "middag",
      "qty": "250 ml",
      "name": "Balsamicokrem",
      "aria": "Balsamicokrem kjøpt",
      "product": "<a href=\"https://smakavitalia.no/crema-allaceto-balsamico-di-modena-igp-150ml-acetaia-malpighi\" target=\"_blank\" rel=\"noopener\">Acetaia Malpighi Crema all&#x27;aceto balsamico di Modena IGP</a>",
      "price": 168,
      "buy": "2 × 84 kr (150 ml)"
    },
    {
      "id": "oliven",
      "vendor": "smak",
      "meal": "middag",
      "qty": "1,2 kg avrent",
      "name": "Oliven",
      "aria": "Oliven kjøpt",
      "product": "<a href=\"https://smakavitalia.no/olive-verdi-1-kg-oko-la-selva\" target=\"_blank\" rel=\"noopener\">La Selva Olive verdi Øko (med stein, i saltlake)</a>",
      "price": 298,
      "buy": "2 × 149 kr (1 kg glass (600 g avrent))",
      "note": "2 glass = nøyaktig 1,2 kg avrent – ta et tredje glass hvis det blir snacking. Med stein."
    },
    {
      "id": "artisjokker",
      "vendor": "smak",
      "meal": "middag",
      "qty": "800 g avrent",
      "name": "Marinerte artisjokker",
      "aria": "Marinerte artisjokker kjøpt",
      "product": "<a href=\"https://smakavitalia.no/Produkt/1/8018759000204/Carciofi-sottolio-doliva-280g-%C3%98KO-La-Selva\" target=\"_blank\" rel=\"noopener\">La Selva Carciofi sott&#x27;olio d&#x27;oliva Øko</a>",
      "price": 680,
      "buy": "5 × 136 kr (280 g glass (ca. 175 g avrent))",
      "note": "Avrent vekt anslått til ca. 175 g/glass; 5 glass ≈ 875 g."
    },
    {
      "id": "kjottdeig",
      "vendor": "oda",
      "meal": "middag",
      "qty": "3,6 kg",
      "name": "Kjøttdeig, storfe + svin",
      "aria": "Kjøttdeig, storfe + svin kjøpt",
      "product": "<a href=\"https://oda.com/no/products/63590-var-laveste-pris-kjottdeig-av-storfe-14/\" target=\"_blank\" rel=\"noopener\">Vår Laveste Pris Kjøttdeig av storfe 14 % (5 pk) + Grilstad Kjøttdeig av svin (4 pk)</a>",
      "price": 569,
      "buy": "5 × 69,90 + 4 × 54,80 kr (400 g)",
      "note": "5 pk storfe 14 % (69,90) + 4 pk svinekjøttdeig (54,80) = 3,6 kg. Kun til polpette – lasagnens ragù er utgått."
    },
    {
      "id": "kyllinglar",
      "vendor": "oda",
      "meal": "middag",
      "qty": "6,0 kg",
      "name": "Utbeinede kyllinglår",
      "aria": "Utbeinede kyllinglår kjøpt",
      "product": "<a href=\"https://oda.com/no/products/64293-ytteroy-larbiff-av-kylling-naturell/\" target=\"_blank\" rel=\"noopener\">Ytterøy Lårbiff av kylling naturell (lårfilet uten skinn og bein)</a>",
      "price": 1303,
      "buy": "7 × 186,2 kr (900 g)",
      "note": "Lårfilet uten skinn – utbeinet lår med skinn finnes ikke hos Oda.",
      "priceText": "1 303 kr"
    },
    {
      "id": "helmelk",
      "vendor": "oda",
      "meal": "middag",
      "qty": "1 l",
      "name": "Helmelk",
      "aria": "Helmelk kjøpt",
      "product": "<a href=\"https://oda.com/no/products/437-tine-helmelk/\" target=\"_blank\" rel=\"noopener\">Tine Helmelk</a>",
      "price": 24,
      "buy": "1 × 24 kr (1 l)",
      "note": "Kun til polpettefarsen (350 ml til brødet) – béchamel er utgått."
    },
    {
      "id": "egg",
      "vendor": "oda",
      "meal": "middag",
      "qty": "9 stk (kjøp 12)",
      "name": "Egg",
      "aria": "Egg kjøpt",
      "product": "<a href=\"https://oda.com/no/products/28870-prior-frokostegg-fra-frittgaende-honer/\" target=\"_blank\" rel=\"noopener\">Prior Frokostegg fra frittgående høner, str L</a>",
      "price": 62,
      "buy": "1 × 62 kr (12 stk)",
      "note": "6 til polpettefarsen + 3 til hjemmelaget aioli; 3 i margin."
    },
    {
      "id": "smor",
      "vendor": "oda",
      "meal": "middag",
      "qty": "150 g",
      "name": "Smør",
      "aria": "Smør kjøpt",
      "product": "<a href=\"https://oda.com/no/products/130-tine-ekte-meierismor/\" target=\"_blank\" rel=\"noopener\">Tine Ekte meierismør</a>",
      "price": 62,
      "buy": "1 × 61,5 kr (500 g)",
      "note": "Til karamellisert løk – béchamel er utgått."
    },
    {
      "id": "solsikkeolje",
      "vendor": "oda",
      "meal": "middag",
      "qty": "850 ml",
      "name": "Solsikkeolje (til aioli)",
      "aria": "Solsikkeolje kjøpt",
      "product": "<a href=\"https://oda.com/no/products/30090-r-solsikkeolje/\" target=\"_blank\" rel=\"noopener\">R Solsikkeolje</a>",
      "price": 43,
      "buy": "1 × 43,4 kr (1 l)",
      "note": "Aiolien lages nå fra bunnen med egg og solsikkeolje – kjøpt majones er utgått."
    },
    {
      "id": "ciabatta",
      "vendor": "oda",
      "meal": "middag",
      "qty": "2,6 kg",
      "name": "Ciabatta / lyst brød",
      "aria": "Ciabatta / lyst brød kjøpt",
      "product": "<a href=\"https://oda.com/no/products/29445-korn-bakeri-fransk-bondebrod/\" target=\"_blank\" rel=\"noopener\">Korn Bakeri Fransk bondebrød</a>",
      "price": 240,
      "buy": "4 × 59,9 kr (700 g)",
      "note": "Til bruschettaen – bondebrødet er besluttet produkt. Lunsjens surdeigs-ciabatta bestilles separat hos bakeri (se lunsjgruppen)."
    },
    {
      "id": "salami-milano",
      "vendor": "oda",
      "meal": "middag",
      "qty": "800 g",
      "name": "Salami Milano",
      "aria": "Salami Milano kjøpt",
      "product": "<a href=\"https://oda.com/no/products/69413-taga-salami-milano/\" target=\"_blank\" rel=\"noopener\">Taga Salami Milano, skivet</a>",
      "price": 449,
      "buy": "10 × 44,9 kr (80 g)",
      "note": "Finnes ikke hos Smak av Italia – kjøpes hos Oda."
    },
    {
      "id": "pinjekjerner",
      "vendor": "oda",
      "meal": "middag",
      "qty": "250 g",
      "name": "Pinjekjerner",
      "aria": "Pinjekjerner kjøpt",
      "product": "<a href=\"https://oda.com/no/products/57629-pinjekjerner/\" target=\"_blank\" rel=\"noopener\">Pinjekjerner (Oda)</a>",
      "price": 234,
      "buy": "5 × 46,9 kr (50 g)",
      "note": "Finnes ikke hos Smak av Italia – kjøpes hos Oda."
    },
    {
      "id": "torrgjaer",
      "vendor": "oda",
      "meal": "middag",
      "qty": "35 g",
      "name": "Tørrgjær",
      "aria": "Tørrgjær kjøpt",
      "product": "<a href=\"https://oda.com/no/products/33918-idun-mh-torrgjaer-original-5-poser/\" target=\"_blank\" rel=\"noopener\">Idun Mh Tørrgjær original</a>",
      "price": 21,
      "buy": "1 × 20,6 kr (5 poser / 65 g)"
    },
    {
      "id": "sukker",
      "vendor": "oda",
      "meal": "middag",
      "qty": "100 g",
      "name": "Sukker",
      "aria": "Sukker kjøpt",
      "product": "<a href=\"https://oda.com/no/products/7813-dansukker-sukker/\" target=\"_blank\" rel=\"noopener\">Dansukker Sukker</a>",
      "price": 37,
      "buy": "1 × 37,1 kr (1 kg)",
      "note": "Til focaccia (60 g) og lunsjens karamelliserte løk. Pastaens syltelake er utgått."
    },
    {
      "id": "salt-fint",
      "vendor": "oda",
      "meal": "middag",
      "qty": "1,0 kg",
      "name": "Fint salt",
      "aria": "Fint salt kjøpt",
      "product": "<a href=\"https://oda.com/no/products/1027-jozo-fint-salt-uten-jod/\" target=\"_blank\" rel=\"noopener\">Jozo Fint salt uten jod</a>",
      "price": 15,
      "buy": "1 × 15,1 kr (1 kg)"
    },
    {
      "id": "flaksalt",
      "vendor": "oda",
      "meal": "middag",
      "qty": "ca. 150 g",
      "name": "Flaksalt",
      "aria": "Flaksalt kjøpt",
      "product": "<a href=\"https://oda.com/no/products/582-maldon-maldonsalt/\" target=\"_blank\" rel=\"noopener\">Maldon Maldonsalt</a>",
      "price": 39,
      "buy": "1 × 38,7 kr (250 g)"
    },
    {
      "id": "pepper",
      "vendor": "oda",
      "meal": "middag",
      "qty": "1 stk",
      "name": "Svart pepper",
      "aria": "Svart pepper kjøpt",
      "product": "<a href=\"https://oda.com/no/products/550-santa-maria-black-pepper-tellicherry-med-kvern/\" target=\"_blank\" rel=\"noopener\">Santa Maria Black Pepper Tellicherry med kvern</a>",
      "price": 80,
      "buy": "1 × 79,5 kr (70 g)"
    },
    {
      "id": "oregano",
      "vendor": "oda",
      "meal": "middag",
      "qty": "1 glass",
      "name": "Tørket oregano",
      "aria": "Tørket oregano kjøpt",
      "product": "<a href=\"https://oda.com/no/products/6274-toro-oregano/\" target=\"_blank\" rel=\"noopener\">Toro Oregano</a>",
      "price": 25,
      "buy": "1 × 25,1 kr (10 g)"
    },
    {
      "id": "chiliflak",
      "vendor": "oda",
      "meal": "middag",
      "qty": "1 glass",
      "name": "Chiliflak",
      "aria": "Chiliflak kjøpt",
      "product": "<a href=\"https://oda.com/no/products/29673-helios-chiliflak-okologisk/\" target=\"_blank\" rel=\"noopener\">Helios Chiliflak økologisk</a>",
      "price": 35,
      "buy": "1 × 34,8 kr (23 g)"
    },
    {
      "id": "rodvinseddik",
      "vendor": "oda",
      "meal": "middag",
      "qty": "250 ml",
      "name": "Rødvinseddik",
      "aria": "Rødvinseddik kjøpt",
      "product": "<a href=\"https://oda.com/no/products/32491-il-torrione-rodvinseddik/\" target=\"_blank\" rel=\"noopener\">Il Torrione Rødvinseddik</a>",
      "price": 39,
      "buy": "1 × 39,4 kr (250 ml)",
      "note": "Bruschetta 70 ml + verdure 100 ml + skvett til lunsjens løk. Pastaens syltelake er utgått – rødløken brukes rå."
    },
    {
      "id": "tomater",
      "vendor": "oda",
      "meal": "middag",
      "qty": "6,5 kg",
      "name": "Modne tomater",
      "aria": "Modne tomater kjøpt",
      "product": "<a href=\"https://oda.com/no/products/60593-tomater-klase-norge-mijogartneriet/\" target=\"_blank\" rel=\"noopener\">Tomater klase, Miljøgartneriet (Norge)</a>",
      "price": 454,
      "buy": "13 × 34,9 kr (500 g)"
    },
    {
      "id": "cherrytomater",
      "vendor": "oda",
      "meal": "middag",
      "qty": "2,75 kg",
      "name": "Cherrytomater",
      "aria": "Cherrytomater kjøpt",
      "product": "<a href=\"https://oda.com/no/products/63848-cherrytomater-var-laveste-pris-nederland-spania/\" target=\"_blank\" rel=\"noopener\">Cherrytomater – Vår laveste pris (Nederland/Spania)</a>",
      "price": 219,
      "buy": "11 × 19,9 kr (250 g)",
      "note": "Pastaen bruker 2,5 kg (skalert opp). Prisen er kampanje t.o.m. 31.8."
    },
    {
      "id": "fersken",
      "vendor": "oda",
      "meal": "middag",
      "qty": "2,5 kg (ca. 16–18 stk)",
      "name": "Fersken",
      "aria": "Fersken kjøpt",
      "product": "<a href=\"https://oda.com/no/products/21643-fersken-kurv-italia-spania/\" target=\"_blank\" rel=\"noopener\">Fersken kurv (Italia/Spania)</a>",
      "price": 250,
      "buy": "3 × 83,2 kr (1 kg kurv)",
      "note": "Leveres onsdag og serveres ferske lørdag – la dem modne i romtemperatur til de gir litt etter for et lett trykk."
    },
    {
      "id": "avokado",
      "vendor": "oda",
      "meal": "middag",
      "qty": "16 stk (små, ca. 2,0 kg)",
      "name": "Avokado, spisemodne",
      "aria": "Avokado kjøpt",
      "product": "<a href=\"https://oda.com/no/products/64198-avokado-spisemoden-columbia-chile-peru/\" target=\"_blank\" rel=\"noopener\">Avokado Spisemoden (Colombia/Chile/Peru)</a>",
      "price": 240,
      "buy": "4 × 59,9 kr (4 stk / ca. 500 g)",
      "note": "Ny i sommersalaten. Leveres onsdag; skjæres i skiver først ved montering lørdag."
    },
    {
      "id": "aubergine",
      "vendor": "oda",
      "meal": "middag",
      "qty": "2,0 kg (ca. 4–5 stk)",
      "name": "Aubergine",
      "aria": "Aubergine kjøpt",
      "product": "<a href=\"https://oda.com/no/products/9392-aubergine-spania-nederland/\" target=\"_blank\" rel=\"noopener\">Aubergine (Spania/Nederland)</a>",
      "price": 84,
      "buy": "5 × 16,9 kr (1 stk (ca. 400 g))"
    },
    {
      "id": "squash",
      "vendor": "oda",
      "meal": "middag",
      "qty": "2,0 kg (ca. 6–8 stk)",
      "name": "Squash",
      "aria": "Squash kjøpt",
      "product": "<a href=\"https://oda.com/no/products/9287-squash-gronn-spania-nederland/\" target=\"_blank\" rel=\"noopener\">Squash grønn (Spania/Nederland)</a>",
      "price": 151,
      "buy": "6 × 25,2 kr (1 stk (ca. 355 g))"
    },
    {
      "id": "paprika",
      "vendor": "oda",
      "meal": "middag",
      "qty": "2,5 kg (ca. 8–10 stk)",
      "name": "Paprika",
      "aria": "Paprika kjøpt",
      "product": "<a href=\"https://oda.com/no/products/27016-paprika-rod-var-laveste-pris-spania-nederland/\" target=\"_blank\" rel=\"noopener\">Paprika rød – Vår laveste pris (Spania/Nederland)</a>",
      "price": 210,
      "buy": "5 × 41,9 kr (600 g)"
    },
    {
      "id": "fennikel",
      "vendor": "oda",
      "meal": "middag",
      "qty": "1,2 kg (4 store)",
      "name": "Fennikel",
      "aria": "Fennikel kjøpt",
      "product": "<a href=\"https://oda.com/no/products/9572-fennikel-italia-tyskland/\" target=\"_blank\" rel=\"noopener\">Fennikel (Italia/Tyskland)</a>",
      "price": 145,
      "buy": "4 × 36,2 kr (1 stk (ca. 340 g))"
    },
    {
      "id": "rodlok",
      "vendor": "oda",
      "meal": "middag",
      "qty": "2,0 kg",
      "name": "Rødløk",
      "aria": "Rødløk kjøpt",
      "product": "<a href=\"https://oda.com/no/products/19630-rodlok-laveste-pris-nederland-egypt/\" target=\"_blank\" rel=\"noopener\">Rødløk – Laveste pris (Nederland/Egypt)</a>",
      "price": 94,
      "buy": "2 × 46,9 kr (1 kg)"
    },
    {
      "id": "gul-lok",
      "vendor": "oda",
      "meal": "middag",
      "qty": "2,0 kg",
      "name": "Gul løk",
      "aria": "Gul løk kjøpt",
      "product": "<a href=\"https://oda.com/no/products/19627-gul-lok-var-laveste-pris-nerderland-danmark/\" target=\"_blank\" rel=\"noopener\">Gul løk – Vår laveste pris (Nederland/Danmark)</a>",
      "price": 70,
      "buy": "2 × 34,9 kr (1 kg)",
      "note": "Tomatbase 800 g + polpette 350 g; lunsjens løk står i lunsjgruppen."
    },
    {
      "id": "hvitlok",
      "vendor": "oda",
      "meal": "middag",
      "qty": "500 g",
      "name": "Hvitløk",
      "aria": "Hvitløk kjøpt",
      "product": "<a href=\"https://oda.com/no/products/9371-hvitlok-2-3pk-kina-spania/\" target=\"_blank\" rel=\"noopener\">Hvitløk 2–3 pk, Kina/Spania</a>",
      "price": 71,
      "buy": "5 × 14,2 kr (100 g (2–3 hele løk))"
    },
    {
      "id": "sitroner",
      "vendor": "oda",
      "meal": "middag",
      "qty": "40 stk",
      "name": "Sitroner",
      "aria": "Sitroner kjøpt",
      "product": "<a href=\"https://oda.com/no/products/37538-sma-sitroner-var-laveste-pris-egypt-argentina/\" target=\"_blank\" rel=\"noopener\">Små sitroner i pose, Egypt/Argentina</a>",
      "price": 209,
      "buy": "7 × 29,9 kr (500 g (ca. 6 stk))",
      "note": "7 poser à 500 g småsitroner ≈ 40–42 stk."
    },
    {
      "id": "loff-brodsmuler",
      "vendor": "manuelt",
      "meal": "middag",
      "qty": "1 brød (ca. 700 g)",
      "name": "Loff / lyst brød til brødsmuler",
      "aria": "Loff til brødsmuler kjøpt",
      "product": "Bakeri eller dagligvare",
      "price": 50,
      "buy": "1 × ca. 50 kr",
      "note": "Erstatter griljermel i polpettene (550 g brød uten skorpe rives og bløtlegges i melk). Kjøp tirsdag/onsdag – dagsgammelt brød rives lettest.",
      "priceText": "ca. 50 kr"
    },
    {
      "id": "feldsalat",
      "vendor": "manuelt",
      "meal": "middag",
      "qty": "600 g",
      "name": "Feldsalatmiks (vårsalat/mâche)",
      "aria": "Feldsalatmiks kjøpt",
      "product": "<a href=\"https://meny.no/varer/frukt-gront/gronnsaker/gronnsaksmikser/salatblanding/feldsalat-mix-7023026089432\" target=\"_blank\" rel=\"noopener\">Grønn&amp;Frisk Feldsalat Mix 65 g (Meny)</a>",
      "price": 100,
      "buy": "10 × 10 kr (65 g pose)",
      "note": "Erstatter ruccolaen i sommersalaten. Kjøpes hos Meny fredag – feldsalat er mer ømfintlig enn ruccola."
    },
    {
      "id": "basilikum",
      "vendor": "manuelt",
      "meal": "middag",
      "qty": "700 g",
      "name": "Frisk basilikum",
      "aria": "Frisk basilikum kjøpt",
      "product": "<a href=\"https://oda.com/no/products/15157-fersk-basilikum-i-pose-etiopia-kenya/\" target=\"_blank\" rel=\"noopener\">Basilikum i stor bunt hos grønnsakshandler (Grønland)</a>",
      "price": 245,
      "buy": "7 × 35 kr (ca. 100 g bunt)",
      "note": "Anslått buntpris hos grønnsakshandler (ca. 35 kr/100 g). Odas 20 g-poser ville kostet ca. 750 kr for samme mengde. Økt fra 600 g – sommersalaten bruker nå 100 g basilikum. Kjøp nær bruksdag.",
      "priceText": "ca. 245 kr"
    },
    {
      "id": "bladpersille",
      "vendor": "manuelt",
      "meal": "middag",
      "qty": "600 g",
      "name": "Bladpersille",
      "aria": "Bladpersille kjøpt",
      "product": "<a href=\"https://oda.com/no/products/17767-fersk-bladpersille-i-pose-etiopia-kenya/\" target=\"_blank\" rel=\"noopener\">Bladpersille i stor bunt hos grønnsakshandler (Grønland)</a>",
      "price": 120,
      "buy": "6 × 20 kr (ca. 100 g bunt)",
      "note": "Anslått buntpris hos grønnsakshandler.",
      "priceText": "ca. 120 kr"
    },
    {
      "id": "rosmarin",
      "vendor": "manuelt",
      "meal": "middag",
      "qty": "150 g",
      "name": "Frisk rosmarin",
      "aria": "Frisk rosmarin kjøpt",
      "product": "<a href=\"https://oda.com/no/products/17749-fersk-rosmarin-i-pose-etiopia-kenya/\" target=\"_blank\" rel=\"noopener\">Rosmarin i bunt hos grønnsakshandler (Grønland)</a>",
      "price": 60,
      "buy": "2 × 30 kr (ca. 75 g bunt)",
      "note": "Anslått buntpris hos grønnsakshandler.",
      "priceText": "ca. 60 kr"
    },
    {
      "id": "timian",
      "vendor": "manuelt",
      "meal": "middag",
      "qty": "100 g",
      "name": "Frisk timian",
      "aria": "Frisk timian kjøpt",
      "product": "<a href=\"https://oda.com/no/products/17752-fersk-timian-i-pose-etiopia-kenya/\" target=\"_blank\" rel=\"noopener\">Timian i bunt hos grønnsakshandler (Grønland)</a>",
      "price": 60,
      "buy": "2 × 30 kr (ca. 50 g bunt)",
      "note": "Anslått buntpris hos grønnsakshandler.",
      "priceText": "ca. 60 kr"
    },
    {
      "id": "laks",
      "vendor": "manuelt",
      "meal": "middag",
      "qty": "4,75 kg (3 hele sider)",
      "name": "Fersk laks, 3 hele sider",
      "aria": "Fersk laks, 3 hele sider kjøpt",
      "product": "<a href=\"https://oda.com/no/products/24888-domstein-laksefilet-med-skinn-oppdrett-fersk/\" target=\"_blank\" rel=\"noopener\">Domstein Laksefilet med skinn, oppdrett, fersk</a>",
      "price": 1812,
      "buy": "ca. 4,8 kg × 377,50 kr/kg (Oda-referanse)",
      "note": "Bestilles hos fiskehandler (f.eks. Fjelberg eller Georg A. Nilsen) senest mandag 17.8 – be om pinnebein fjernet. Ingen fiskehandler har nettpris på hele sider; prisen er Oda-referanse (377,50 kr/kg). Forvent 250–380 kr/kg hos fiskehandler.",
      "priceText": "1 812 kr"
    },
    {
      "id": "rodvin",
      "vendor": "manuelt",
      "meal": "middag",
      "qty": "750 ml (1 flaske)",
      "name": "Rødvin til tomatbasen",
      "aria": "Rødvin til tomatbasen kjøpt",
      "product": "<a href=\"https://www.vinmonopolet.no/Land/Italia/Abruzzo/Montepulciano-d%27Abruzzo/Piccini-Montepulciano-d%27Abruzzo-2024/p/366901\" target=\"_blank\" rel=\"noopener\">Piccini Montepulciano d&#x27;Abruzzo 2024</a>",
      "price": 148,
      "buy": "1 × 147,9 kr (750 ml)",
      "note": "Tørr, fruktig Montepulciano – egnet i tomatsaus. Halvert base trenger 625 ml. Kjøpes på Vinmonopolet."
    },
    {
      "id": "lunsj-biff",
      "vendor": "oda",
      "meal": "lunsj",
      "qty": "6,0 kg (3 stk)",
      "name": "Ytrefilet av storfe, hele stykker – <strong>produkt TBD</strong>",
      "aria": "Ytrefilet til lunsj kjøpt",
      "product": "Endelig produkt under avklaring: <a href=\"https://oda.com/no/products/15262-strom-larsen-hel-ytrefilet-av-storfe/\" target=\"_blank\" rel=\"noopener\">Str&#248;m-Larsen hel ytrefilet via Oda</a> (2 722 kr) eller modnet ytrefilet fra <a href=\"https://polsemakeri.no/produkt-kategori/kjott/storfe/\" target=\"_blank\" rel=\"noopener\">Annis P&#248;lsemakeri</a> (pris bekreftes)",
      "price": 2722,
      "buy": "3 × ca. 2 kg",
      "note": "Uansett produkt: 3 hele, renskårne stykker à ca. 2 kg – ikke oppskåret. Langtidsstekes hele (reverse sear), brunes hardt og skjæres tynt fortløpende under service. 43 porsjoner à ca. 140 g rå (2 gjester får vegetarvarianten). Prisen i summen er Oda-referansen; Annis blir dyrere.",
      "priceText": "fra 2 722 kr"
    },
    {
      "id": "lunsj-brod",
      "vendor": "manuelt",
      "meal": "lunsj",
      "qty": "48 stk à ca. 120 g (ca. 5,8 kg)",
      "name": "Surdeigs-ciabatta til lunsj – <strong>bestilles hos bakeri</strong>",
      "aria": "Surdeigs-ciabatta til lunsj bestilt",
      "product": "Spesialbestilling hos bakeri (originalen bruker «freshly baked sourdough ciabatta»)",
      "price": 1200,
      "buy": "48 × ca. 25 kr",
      "note": "45 porsjoner + 3 i reserve; individuelle ciabatta à 120–130 g som deles og ristes ved montering. Avtal senest mandag 17.8, hent lørdag morgen. Prisen er anslag – bekreft med bakeriet.",
      "priceText": "ca. 1 200 kr"
    },
    {
      "id": "lunsj-lok",
      "vendor": "oda",
      "meal": "lunsj",
      "qty": "4,0 kg",
      "name": "Gul løk til karamellisering",
      "aria": "Gul løk til karamellisering kjøpt",
      "product": "<a href=\"https://oda.com/no/products/19627-gul-lok-var-laveste-pris-nerderland-danmark/\" target=\"_blank\" rel=\"noopener\">Gul løk – Vår laveste pris (Nederland/Danmark)</a>",
      "price": 140,
      "buy": "4 × 34,9 kr (1 kg)",
      "note": "Gir ca. 1,2 kg karamellisert løk (~27 g per porsjon). Karamelliseres i olivenolje og ca. 100 g smør fra marginene."
    },
    {
      "id": "lunsj-tomater",
      "vendor": "oda",
      "meal": "lunsj",
      "qty": "2,0 kg",
      "name": "Modne tomater til sandwichene",
      "aria": "Tomater til sandwichene kjøpt",
      "product": "<a href=\"https://oda.com/no/products/60593-tomater-klase-norge-mijogartneriet/\" target=\"_blank\" rel=\"noopener\">Tomater klase, Miljøgartneriet (Norge)</a>",
      "price": 140,
      "buy": "4 × 34,9 kr (500 g)",
      "note": "Ca. 2 skiver per sandwich. Buffetens 6,5 kg er dimensjonert for caprese og bruschetta – ikke ta derfra."
    },
    {
      "id": "lunsj-dijon",
      "vendor": "oda",
      "meal": "lunsj",
      "qty": "2 glass (760 g)",
      "name": "Dijonsennep",
      "aria": "Dijonsennep kjøpt",
      "product": "<a href=\"https://oda.com/no/products/545-maille-dijonsennep-original/\" target=\"_blank\" rel=\"noopener\">Maille Dijonsennep Original</a>",
      "price": 70,
      "buy": "2 × 34,8 kr (380 g)",
      "note": "Smøres på brødet; ca. 10 g per sandwich gir god margin. Rester brukes til nattmaten."
    },
    {
      "id": "lunsj-ruccola",
      "vendor": "oda",
      "meal": "lunsj",
      "qty": "350 g",
      "name": "Ruccola til sandwichene",
      "aria": "Ruccola til lunsj kjøpt",
      "product": "<a href=\"https://oda.com/no/products/61764-okologisk-ruccula-norge/\" target=\"_blank\" rel=\"noopener\">Økologisk Ruccula, Norge</a>",
      "price": 176,
      "buy": "7 × 25,1 kr (50 g)",
      "note": "Til lunsjsandwichene. Sommersalaten bruker nå feldsalat, så dette er eneste ruccola-innkjøp."
    },
    {
      "id": "lunsj-mozzarella",
      "vendor": "smak",
      "meal": "lunsj",
      "qty": "125 g (1 kule)",
      "name": "Mozzarella til vegetar-ciabatta",
      "aria": "Mozzarella til vegetar-ciabatta kjøpt",
      "product": "<a href=\"https://smakavitalia.no/Produkt/126/809951909/Mozzarella-di-Bufala-Campana-DOP-125gr-Campania-Felix\" target=\"_blank\" rel=\"noopener\">Mozzarella di Bufala Campana DOP 125 g – Campania Felix</a>",
      "price": 39,
      "buy": "1 × 39 kr (125 g kule i lake)",
      "note": "Reserver 17 kuler i stedet for 16 når du ringer Smak av Italia – capresens 2,0 kg skal ikke røres."
    },
    {
      "id": "natt-polser",
      "vendor": "oda",
      "meal": "nattmat",
      "qty": "6,0 kg (ca. 100 stk)",
      "name": "Grill-/wienerpølser, gluten- og laktosefrie",
      "aria": "Grillpølser/wienerpølser kjøpt",
      "product": "<a href=\"https://oda.com/no/products/40419-gilde-grillpolser-2-pk-2x600g/\" target=\"_blank\" rel=\"noopener\">Gilde Grillpølser 2 pk (2 × 600 g)</a>",
      "price": 360,
      "buy": "5 × 71,9 kr (1,2 kg)",
      "note": "Gilde Grillpølser er merket gluten- og laktosefrie – dobbeltsjekk etiketten ved levering. Ca. 2 pølser per sen gjest."
    },
    {
      "id": "natt-kyllingpolser",
      "vendor": "oda",
      "meal": "nattmat",
      "qty": "1 pk (460 g)",
      "name": "Kyllingpølser",
      "aria": "Kyllingpølser kjøpt",
      "product": "<a href=\"https://oda.com/no/products/61618-solvinge-grillpolser-av-kylling/\" target=\"_blank\" rel=\"noopener\">Solvinge Grillpølser av kylling</a>",
      "price": 44,
      "buy": "1 × 43,7 kr (460 g)",
      "note": "Til gjestene uten svin og uten rødt kjøtt."
    },
    {
      "id": "natt-vegetarpolser",
      "vendor": "oda",
      "meal": "nattmat",
      "qty": "2 pk (480 g)",
      "name": "Vegetarpølser",
      "aria": "Vegetarpølser kjøpt",
      "product": "<a href=\"https://oda.com/no/products/60216-govegan-grillpolse/\" target=\"_blank\" rel=\"noopener\">Go'Vegan Grillpølse</a>",
      "price": 103,
      "buy": "2 × 51,6 kr (240 g)",
      "note": "Til de tre vegetarene, med margin."
    },
    {
      "id": "natt-polsebrod",
      "vendor": "oda",
      "meal": "nattmat",
      "qty": "60 stk",
      "name": "Pølsebrød",
      "aria": "Pølsebrød kjøpt",
      "product": "<a href=\"https://oda.com/no/products/8342-prima-lavpris-polsebrod-12-stk/\" target=\"_blank\" rel=\"noopener\">Prima Lavpris Pølsebrød 12 stk</a>",
      "price": 79,
      "buy": "5 × 15,7 kr (12 stk)"
    },
    {
      "id": "natt-lomper",
      "vendor": "oda",
      "meal": "nattmat",
      "qty": "ca. 48 stk (6 pk)",
      "name": "Lomper",
      "aria": "Lomper kjøpt",
      "product": "<a href=\"https://oda.com/no/products/32194-ola-lompa-store-lomper/\" target=\"_blank\" rel=\"noopener\">Ola Lompa Store lomper</a>",
      "price": 102,
      "buy": "6 × 17 kr (290 g)",
      "note": "NB: vanlige lomper inneholder hvete – de er ikke til glutengjesten."
    },
    {
      "id": "natt-gf-brod",
      "vendor": "oda",
      "meal": "nattmat",
      "qty": "1 pk",
      "name": "Glutenfrie pølsebrød",
      "aria": "Glutenfrie pølsebrød kjøpt",
      "product": "<a href=\"https://oda.com/no/products/28535-fria-polsebrod-glutenfri/\" target=\"_blank\" rel=\"noopener\">Fria Pølsebrød Glutenfri</a>",
      "price": 65,
      "buy": "1 × 65,4 kr (210 g)",
      "note": "Oppbevares og serveres fra egen pose/kurv, adskilt fra hvetebrødet."
    },
    {
      "id": "natt-ketchup",
      "vendor": "oda",
      "meal": "nattmat",
      "qty": "910 g",
      "name": "Ketchup",
      "aria": "Ketchup kjøpt",
      "product": "<a href=\"https://oda.com/no/products/57266-idun-tomatketchup/\" target=\"_blank\" rel=\"noopener\">Idun Tomatketchup</a>",
      "price": 35,
      "buy": "1 × 34,9 kr (910 g)"
    },
    {
      "id": "natt-sennep",
      "vendor": "oda",
      "meal": "nattmat",
      "qty": "490 g",
      "name": "Mild sennep",
      "aria": "Mild sennep kjøpt",
      "product": "<a href=\"https://oda.com/no/products/570-idun-polsesennep/\" target=\"_blank\" rel=\"noopener\">Idun Pølsesennep</a>",
      "price": 24,
      "buy": "1 × 24 kr (490 g)"
    }
  ]
};
